.. highlight:: bash
.. |project_name| replace:: AppFlow
.. |package_dirname| replace:: appflow-|version|
.. |package_filename| replace:: |package_dirname|.tar.gz
.. |package_url| replace:: https://pypi.python.org/packages/source/b/ttssdev/|package_filename|
.. |git_url| replace:: https://github.com/ttssdev/appflow.git
.. _github: https://github.com/ttssdev/appflow
.. _issue tracker: https://github.com/ttssdev/appflow/issues